// Mocks generated by Mockito 5.4.6 from annotations
// in wallpaper_downloader/test/modules/home_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wallpaper_downloader/data/models/api_response.dart' as _i2;
import 'package:wallpaper_downloader/data/models/wallpaper_model.dart' as _i5;
import 'package:wallpaper_downloader/data/repositories/wallpaper_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WallpaperRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWallpaperRepository extends _i1.Mock
    implements _i3.WallpaperRepository {
  @override
  _i4.Future<_i2.ApiResponse<List<_i5.WallpaperModel>>> getWallpapers({
    required String? query,
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWallpapers, [], {#query: query, #page: page}),
            returnValue:
                _i4.Future<_i2.ApiResponse<List<_i5.WallpaperModel>>>.value(
                  _FakeApiResponse_0<List<_i5.WallpaperModel>>(
                    this,
                    Invocation.method(#getWallpapers, [], {
                      #query: query,
                      #page: page,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.ApiResponse<List<_i5.WallpaperModel>>>.value(
                  _FakeApiResponse_0<List<_i5.WallpaperModel>>(
                    this,
                    Invocation.method(#getWallpapers, [], {
                      #query: query,
                      #page: page,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<List<_i5.WallpaperModel>>>);
}
